name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          node -v
          npm -v
  # parallel-job-windows:
  #  runs-on: windows-latest
  #  steps:
  #   - name: View OS Version
  #     run: systeminfo

  # dependant-job:
  #   runs-on: windows-latest
  #   needs: run-shell-commands
  #   steps:
  #     - name: echo a string
  #       run: Write-Output "Windows String"
  #     - name: Error Step
  #       run: does not exists
