name: Working Dirs & Shells
on: [push]

defaults:
  run:
    shell: bash

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo "SHA: $GITHUB_SHA"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Workspace: $GITHUB_WORKSPACE"

      - name: Change Working Directory
        working-directory: ${{ github.workspace }}
        run: pwd

  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display Working Directory & List Files
        run: |
          Get-Location
          dir
          Write-Output "SHA: $env:GITHUB_SHA"
          Write-Output "Repository: $env:GITHUB_REPOSITORY"
          Write-Output "Workspace: $env:GITHUB_WORKSPACE"

      - name: Python Shell Execution
        run: python -c "import platform; print(platform.processor())"
