name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
    branches:
      - main
jobs:
  echo-string:
    runs-on: windows-latest
    steps:
      - run: echo "I was triggered because 'Repository Events' was completed"
